using Microsoft.EntityFrameworkCore;

namespace Word.Infrastructure.Persistence.Seed;

public static class AuthSchemaInitializer
{
    public static async Task InitializeAsync(
        AppDbContext context,
        CancellationToken cancellationToken = default)
    {
        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "Users" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(200) NOT NULL,
                "Email" character varying(200) NOT NULL,
                "GoogleId" character varying(200),
                "PasswordHash" character varying(500),
                "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW(),
                "LastLoginAtUtc" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """,
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "Users"
            ADD COLUMN IF NOT EXISTS "PasswordHash" character varying(500);
            """,
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "Users"
            ALTER COLUMN "GoogleId" DROP NOT NULL;
            """,
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email"
            ON "Users" ("Email");
            """,
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_GoogleId"
            ON "Users" ("GoogleId");
            """,
            cancellationToken);
    }
}
